openapi: 3.0.1
info:
  title: Primo Lead Saver
  version: "1.0.0"
servers:
  - url: https://script.google.com/macros/s/AKfycbwxmnV4wTImq6MPIrGGUEvH11U37MLApZuitpZpdhZ9LdQPlorsVc5A0zb5fl0NG7aT
paths:
  /exec:
    post:
      operationId: saveLead
      summary: Save a lead into Google Sheets (PRIMO LLC / TRIALS)
      description: |
        Appends one row to the "TRIALS" tab with columns:
        [ID, NAME, EMAIL, WHATSAPP, PLAN, DATE, DONE ?, NOTES].
        Send JSON with action=saveLead.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [action, name]
              properties:
                action:
                  type: string
                  enum: [saveLead]
                  example: saveLead
                id:
                  type: string
                  description: Optional. Use chat_id or any unique id; backend generates one if omitted.
                name:
                  type: string
                  description: Full name
                email:
                  type: string
                  format: email
                whatsapp:
                  type: string
                  description: E.164 or any text
                phone:
                  type: string
                  description: Fallback for whatsapp; backend maps phone→whatsapp if provided
                plan:
                  type: string
                  description: e.g., Trial, 1m Essential, 6m VIP, 12m VIP
                date:
                  type: string
                  description: ISO date; defaults to today if omitted
                done:
                  type: boolean
                  description: Sets the DONE ? checkbox (default false)
                notes:
                  type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  saved:
                    type: boolean
                  row:
                    type: integer
                  id:
                    type: string
