openapi: "3.0.0"
info:
  version: 1.0.0
  title: Google Sheets Submit API
  description: >
    This API submits customer lead information to a Google Sheet.
  license:
    name: MIT
servers:
  - url: https://script.google.com/macros/s/AKfycbxNo5AADMjrcBtq50zSZ6ME9k9LLL5iyqKozDbAHzpdw8S--Az8SqFdpdc4emnZzMtS
paths:
  /exec:
    post:
      summary: Submit customer information to Google Sheets
      operationId: submitLead
      requestBody:
        description: Fields to be submitted to the Sheet
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - NAME
                - EMAIL
                - WHATSAPP
              properties:
                NAME:
                  type: string
                  description: Full name of the customer
                  example: "John Doe"
                EMAIL:
                  type: string
                  description: Customer’s email address
                  format: email
                  example: "john@example.com"
                WHATSAPP:
                  type: string
                  description: Customer’s WhatsApp number (include country code)
                  example: "+212612345678"
      responses:
        '200':
          description: Lead submitted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  submitted:
                    type: boolean
                    description: Submission status
                    example: true
                  timestamp:
                    type: string
                    format: date-time
                    description: Time the form was submitted
                    example: "2025-10-04T12:45:30Z"
                  id:
                    type: string
                    description: Unique ID of the submitted row
                    example: "row-27"
                  error:
                    type: string
                    nullable: true
                    description: Error message if submission fails
                    example: null
