openapi: "3.0.0"
info:
  version: 1.0.0
  title: Google Form Submit API
  description: Collects visitor info and sends it to your Google Form
servers:
  - url: "https://script.google.com/macros/s/AKfycbyQ9RAmyPKPNRF2j6BLz91bYU8K59bqtb1_7AY2Jx0JWFmlRCa-RFOdjRMfldy9vu0n"
paths:
  /exec:
    post:
      summary: Submit lead info to Google Form
      operationId: submitLead
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - Full Name
                - Email
                - WhatsApp Number
              properties:
                Full Name:
                  type: string
                  description: Visitor's full name
                Email:
                  type: string
                  description: Visitor's email address
                WhatsApp Number:
                  type: string
                  description: Visitor's WhatsApp phone number
      responses:
        "200":
          description: Successful submission
          content:
            application/json:
              schema:
                type: object
                properties:
                  submitted:
                    type: boolean
                  timestamp:
                    type: string
