openapi: "3.0.0"
info:
  version: 1.0.0
  title: Google Form Submit API
  description: Collects visitor info and sends to your Google Form
servers:
  - url: "https://script.google.com/macros/s/AKfycbzWcGuJkgs3Q1EgUC2BLpadm_sJ22lnrh07Q-htA0NJQ0E9Z739fUC8YKismnkflU0m"
paths:
  /exec:
    post:
      summary: Submit lead info to Google Form
      operationId: submitLead
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - Full Name
                - Email
                - WhatsApp Number
                - Package
              properties:
                Full Name:
                  type: string
                Email:
                  type: string
                WhatsApp Number:
                  type: string
                Package:
                  type: string
                  enum: ["Essential", "ELITE VIP"]
      responses:
        "200":
          description: Successful submission
          content:
            application/json:
              schema:
                type: object
                properties:
                  submitted:
                    type: boolean
                  timestamp:
                    type: string
